"""empty message

Revision ID: 0726f17762e2
Revises: 646b6b190063
Create Date: 2019-02-06 17:21:37.651648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0726f17762e2'
down_revision = '646b6b190063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_department_id_fkey', 'employee', type_='foreignkey')
    op.drop_column('employee', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('employee_department_id_fkey', 'employee', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###
