"""empty message

Revision ID: 3fbffc43318b
Revises: 37fbfe7e883c
Create Date: 2019-02-07 10:37:59.723725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbffc43318b'
down_revision = '37fbfe7e883c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('employee_identification_number_key', 'employee', type_='unique')
    op.drop_column('employee', 'identification_number')
    op.add_column('user', sa.Column('identification_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['identification_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'identification_number')
    op.add_column('employee', sa.Column('identification_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('employee_identification_number_key', 'employee', ['identification_number'])
    op.drop_table('contractor')
    # ### end Alembic commands ###
