"""empty message

Revision ID: 646b6b190063
Revises: 9aa0e1f444e8
Create Date: 2019-02-06 15:52:48.305317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646b6b190063'
down_revision = '9aa0e1f444e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'user_id')
    # ### end Alembic commands ###
