"""empty message

Revision ID: 840daf4878a2
Revises: 6fb829e3b6f1
Create Date: 2019-02-06 15:44:35.760937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840daf4878a2'
down_revision = '6fb829e3b6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('reception_address', sa.String(), nullable=True),
    sa.Column('credit_card_number', sa.String(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('charge', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.drop_table('employee')
    op.drop_table('department')
    op.drop_table('customer')
    # ### end Alembic commands ###
