"""empty message

Revision ID: a7703dc3f1a8
Revises: 6e8ae13a53a7
Create Date: 2019-02-07 09:10:46.878356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7703dc3f1a8'
down_revision = '6e8ae13a53a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'department')
    # ### end Alembic commands ###
